/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/common/Alert.vue')['default']
    AudioPlayer: typeof import('./src/components/display/AudioPlayer.vue')['default']
    Avatar: typeof import('./src/components/common/Avatar.vue')['default']
    Badge: typeof import('./src/components/common/Badge.vue')['default']
    Button: typeof import('./src/components/input/Button.vue')['default']
    Card: typeof import('./src/components/container/Card.vue')['default']
    Chart: typeof import('./src/components/display/Chart.vue')['default']
    CheckBox: typeof import('./src/components/input/CheckBox.vue')['default']
    ChoicePicker: typeof import('./src/components/input/ChoicePicker.vue')['default']
    Column: typeof import('./src/components/layout/Column.vue')['default']
    DateTimeInput: typeof import('./src/components/input/DateTimeInput.vue')['default']
    Divider: typeof import('./src/components/display/Divider.vue')['default']
    Empty: typeof import('./src/components/common/Empty.vue')['default']
    Icon: typeof import('./src/components/display/Icon.vue')['default']
    Image: typeof import('./src/components/display/Image.vue')['default']
    List: typeof import('./src/components/layout/List.vue')['default']
    Modal: typeof import('./src/components/container/Modal.vue')['default']
    Progress: typeof import('./src/components/common/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/layout/Row.vue')['default']
    Skeleton: typeof import('./src/components/common/Skeleton.vue')['default']
    Slider: typeof import('./src/components/input/Slider.vue')['default']
    Spinner: typeof import('./src/components/common/Spinner.vue')['default']
    Switch: typeof import('./src/components/common/Switch.vue')['default']
    Tabs: typeof import('./src/components/container/Tabs.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    Text: typeof import('./src/components/display/Text.vue')['default']
    TextField: typeof import('./src/components/input/TextField.vue')['default']
    Tooltip: typeof import('./src/components/common/Tooltip.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    Video: typeof import('./src/components/display/Video.vue')['default']
  }
}
