/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/common/Alert.vue')['default']
    AudioPlayer: typeof import('./src/components/display/AudioPlayer.vue')['default']
    Avatar: typeof import('./src/components/common/Avatar.vue')['default']
    Badge: typeof import('./src/components/common/Badge.vue')['default']
    Button: typeof import('./src/components/input/Button.vue')['default']
    Card: typeof import('./src/components/container/Card.vue')['default']
    CheckBox: typeof import('./src/components/input/CheckBox.vue')['default']
    ChoicePicker: typeof import('./src/components/input/ChoicePicker.vue')['default']
    Column: typeof import('./src/components/layout/Column.vue')['default']
    DateTimeInput: typeof import('./src/components/input/DateTimeInput.vue')['default']
    Divider: typeof import('./src/components/display/Divider.vue')['default']
    Empty: typeof import('./src/components/common/Empty.vue')['default']
    Icon: typeof import('./src/components/display/Icon.vue')['default']
    Image: typeof import('./src/components/display/Image.vue')['default']
    List: typeof import('./src/components/layout/List.vue')['default']
    Modal: typeof import('./src/components/container/Modal.vue')['default']
    Progress: typeof import('./src/components/common/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/layout/Row.vue')['default']
    Skeleton: typeof import('./src/components/common/Skeleton.vue')['default']
    Slider: typeof import('./src/components/input/Slider.vue')['default']
    Spinner: typeof import('./src/components/common/Spinner.vue')['default']
    Switch: typeof import('./src/components/common/Switch.vue')['default']
    Tabs: typeof import('./src/components/container/Tabs.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    Text: typeof import('./src/components/display/Text.vue')['default']
    TextField: typeof import('./src/components/input/TextField.vue')['default']
    Tooltip: typeof import('./src/components/common/Tooltip.vue')['default']
    Video: typeof import('./src/components/display/Video.vue')['default']
  }
}
